export interface TriviaCard {
  question: string;
  answer: string;
  difficulty: "easy" | "medium" | "hard";
}

export const triviaCards: TriviaCard[] = [
  {
    question: "How many days did God take to create the world before resting?",
    answer: "Six days. He rested on the seventh. (Genesis 2:2)",
    difficulty: "easy",
  },
  {
    question: "Who built the ark that saved his family from the flood?",
    answer: "Noah. (Genesis 6)",
    difficulty: "easy",
  },
  {
    question: "What did David use to defeat Goliath?",
    answer: "A sling and a stone. (1 Samuel 17:49)",
    difficulty: "easy",
  },
  {
    question: "Who was swallowed by a great fish?",
    answer: "Jonah. (Jonah 1:17)",
    difficulty: "easy",
  },
  {
    question: "In which town was Jesus born?",
    answer: "Bethlehem. (Matthew 2:1)",
    difficulty: "easy",
  },
  {
    question: "How many disciples did Jesus choose?",
    answer: "Twelve. (Luke 6:13)",
    difficulty: "easy",
  },
  {
    question: "What is the first book of the Bible?",
    answer: "Genesis.",
    difficulty: "easy",
  },
  {
    question: "Who led the Israelites out of Egypt?",
    answer: "Moses. (Exodus 3-14)",
    difficulty: "easy",
  },
  {
    question: "What sign did God give Noah as a promise never to flood the earth again?",
    answer: "The rainbow. (Genesis 9:13)",
    difficulty: "easy",
  },
  {
    question: "Who betrayed Jesus for thirty pieces of silver?",
    answer: "Judas Iscariot. (Matthew 26:14-15)",
    difficulty: "easy",
  },
  {
    question: "What did Jesus feed to five thousand people?",
    answer: "Five loaves of bread and two fish. (Matthew 14:17-21)",
    difficulty: "easy",
  },
  {
    question: "Who was the strongest man in the Bible, whose strength was in his hair?",
    answer: "Samson. (Judges 16:17)",
    difficulty: "easy",
  },
  {
    question: "How many books are in the whole Bible?",
    answer: "66 books: 39 in the Old Testament and 27 in the New Testament.",
    difficulty: "medium",
  },
  {
    question: "Who was thrown into the lions' den for praying to God?",
    answer: "Daniel. (Daniel 6)",
    difficulty: "easy",
  },
  {
    question: "What was the name of the garden where Adam and Eve lived?",
    answer: "The Garden of Eden. (Genesis 2:8)",
    difficulty: "easy",
  },
  {
    question: "Which sea did Moses part so the Israelites could cross on dry ground?",
    answer: "The Red Sea. (Exodus 14:21-22)",
    difficulty: "easy",
  },
  {
    question: "Who was the first king of Israel?",
    answer: "Saul. (1 Samuel 10:1)",
    difficulty: "medium",
  },
  {
    question: "What are the first three words of the Bible?",
    answer: "\"In the beginning...\" (Genesis 1:1)",
    difficulty: "easy",
  },
  {
    question: "Which disciple walked on water toward Jesus before he began to sink?",
    answer: "Peter. (Matthew 14:29-30)",
    difficulty: "medium",
  },
  {
    question: "Who was the wisest king of Israel, famous for asking God for wisdom?",
    answer: "Solomon. (1 Kings 3:9-12)",
    difficulty: "easy",
  },
  {
    question: "What city's walls fell down after the Israelites marched around it seven times?",
    answer: "Jericho. (Joshua 6)",
    difficulty: "medium",
  },
  {
    question: "Who was sold into slavery by his brothers and later became a ruler in Egypt?",
    answer: "Joseph. (Genesis 37, 41)",
    difficulty: "easy",
  },
  {
    question: "How many days and nights did it rain during the great flood?",
    answer: "Forty days and forty nights. (Genesis 7:12)",
    difficulty: "easy",
  },
  {
    question: "Which two people in the Bible never died?",
    answer: "Enoch and Elijah. (Genesis 5:24, 2 Kings 2:11)",
    difficulty: "medium",
  },
  {
    question: "Who denied Jesus three times before the rooster crowed?",
    answer: "Peter. (Luke 22:61)",
    difficulty: "medium",
  },
  {
    question: "What was Jesus' first miracle?",
    answer: "Turning water into wine at the wedding in Cana. (John 2:1-11)",
    difficulty: "medium",
  },
  {
    question: "Which book of the Bible has the most chapters?",
    answer: "Psalms, with 150 chapters.",
    difficulty: "medium",
  },
  {
    question: "Who wrote most of the letters (epistles) in the New Testament?",
    answer: "The Apostle Paul.",
    difficulty: "medium",
  },
  {
    question: "What is the shortest verse in the Bible?",
    answer: "\"Jesus wept.\" (John 11:35)",
    difficulty: "medium",
  },
  {
    question: "On what mountain did Moses receive the Ten Commandments?",
    answer: "Mount Sinai. (Exodus 19-20)",
    difficulty: "medium",
  },
  {
    question: "Who was the tax collector that climbed a sycamore tree to see Jesus?",
    answer: "Zacchaeus. (Luke 19:1-4)",
    difficulty: "medium",
  },
  {
    question: "What fruit of the Spirit list appears in Galatians 5?",
    answer: "Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control.",
    difficulty: "medium",
  },
  {
    question: "Who was Ruth's mother-in-law, whom she refused to leave?",
    answer: "Naomi. (Ruth 1:16)",
    difficulty: "medium",
  },
  {
    question: "How many plagues did God send on Egypt?",
    answer: "Ten. (Exodus 7-12)",
    difficulty: "medium",
  },
  {
    question: "Which queen risked her life to save the Jewish people from Haman's plot?",
    answer: "Queen Esther. (Esther 4-7)",
    difficulty: "medium",
  },
  {
    question: "What did God provide daily to feed the Israelites in the wilderness?",
    answer: "Manna (and quail). (Exodus 16)",
    difficulty: "medium",
  },
  // ----- Additions: easy -----
  { question: "Who was the first woman?", answer: "Eve. (Genesis 3:20)", difficulty: "easy" },
  { question: "Who killed his brother Abel?", answer: "Cain. (Genesis 4:8)", difficulty: "easy" },
  { question: "What did God create on the very first day?", answer: "Light. (Genesis 1:3)", difficulty: "easy" },
  { question: "In which river was Jesus baptized?", answer: "The Jordan River. (Matthew 3:13)", difficulty: "easy" },
  { question: "Which angel told Mary she would have a son?", answer: "Gabriel. (Luke 1:26-31)", difficulty: "easy" },
  { question: "What gifts did the wise men bring baby Jesus?", answer: "Gold, frankincense, and myrrh. (Matthew 2:11)", difficulty: "easy" },
  { question: "What animal carried Jesus into Jerusalem?", answer: "A donkey. (Matthew 21:7)", difficulty: "easy" },
  { question: "On which day did Jesus rise from the dead?", answer: "The third day. (Luke 24:7)", difficulty: "easy" },
  { question: "Who was the brother of Moses who spoke for him?", answer: "Aaron. (Exodus 4:14-16)", difficulty: "easy" },
  { question: "Who was Abraham's promised son?", answer: "Isaac. (Genesis 21:1-3)", difficulty: "easy" },
  { question: "What bird brought Noah an olive leaf?", answer: "A dove. (Genesis 8:11)", difficulty: "easy" },
  { question: "In which town did Jesus grow up?", answer: "Nazareth. (Luke 2:39-40)", difficulty: "easy" },
  { question: "What were Peter and Andrew doing when Jesus called them?", answer: "Fishing. Jesus said he would make them fishers of men. (Matthew 4:18-19)", difficulty: "easy" },
  { question: "Who is called the father of many nations?", answer: "Abraham. (Genesis 17:4-5)", difficulty: "easy" },
  { question: "What is the last word in the Bible?", answer: "Amen. (Revelation 22:21)", difficulty: "easy" },
  { question: "What tower did people build to reach the heavens?", answer: "The Tower of Babel. (Genesis 11:4-9)", difficulty: "easy" },
  { question: "What is the Golden Rule?", answer: "Do to others as you would have them do to you. (Matthew 7:12)", difficulty: "easy" },
  { question: "Who found baby Moses in a basket on the river?", answer: "Pharaoh's daughter. (Exodus 2:5-6)", difficulty: "easy" },
  { question: "What instrument did David play?", answer: "The harp. (1 Samuel 16:23)", difficulty: "easy" },
  { question: "Who slept through a storm in a boat?", answer: "Jesus, before calming the sea. (Mark 4:38-39)", difficulty: "easy" },
  { question: "What did Jacob dream about at Bethel?", answer: "A stairway to heaven with angels on it. (Genesis 28:12)", difficulty: "easy" },
  { question: "Who were Adam and Eve's first two sons?", answer: "Cain and Abel. (Genesis 4:1-2)", difficulty: "easy" },
  { question: "What prayer begins with \"Our Father in heaven\"?", answer: "The Lord's Prayer. (Matthew 6:9)", difficulty: "easy" },
  { question: "What did the serpent tempt Eve to do?", answer: "Eat fruit from the forbidden tree. (Genesis 3:1-6)", difficulty: "easy" },
  { question: "Who was Jesus' mother?", answer: "Mary. (Luke 1:30-31)", difficulty: "easy" },
  { question: "Who was Jesus' earthly father, a carpenter?", answer: "Joseph. (Matthew 1:16, 13:55)", difficulty: "easy" },
  { question: "What sea did Jesus calm with \"Peace! Be still!\"?", answer: "The Sea of Galilee. (Mark 4:39)", difficulty: "easy" },
  { question: "What are the first four books of the New Testament called?", answer: "The Gospels: Matthew, Mark, Luke, and John.", difficulty: "easy" },
  { question: "How many commandments are there?", answer: "Ten. (Exodus 20)", difficulty: "easy" },
  { question: "Who wrote most of the Psalms?", answer: "King David.", difficulty: "easy" },
  { question: "What did God set in the sky as a promise to Noah?", answer: "A rainbow. (Genesis 9:13)", difficulty: "easy" },
  { question: "Where were Adam and Eve when they hid from God?", answer: "Among the trees of the Garden of Eden. (Genesis 3:8)", difficulty: "easy" },
  { question: "Who did God call from a burning bush?", answer: "Moses. (Exodus 3:4)", difficulty: "easy" },
  { question: "What is the shortest verse in the Bible in many translations?", answer: "\"Jesus wept.\" (John 11:35)", difficulty: "easy" },
  // ----- Additions: medium -----
  { question: "Who was Isaac's wife?", answer: "Rebekah. (Genesis 24:67)", difficulty: "medium" },
  { question: "What new name did God give Jacob?", answer: "Israel, after he wrestled with God. (Genesis 32:28)", difficulty: "medium" },
  { question: "How many sons did Jacob have?", answer: "Twelve, the fathers of the twelve tribes of Israel. (Genesis 35:22)", difficulty: "medium" },
  { question: "What did Esau trade for a bowl of stew?", answer: "His birthright. (Genesis 25:33-34)", difficulty: "medium" },
  { question: "Which prophet faced the prophets of Baal on Mount Carmel?", answer: "Elijah. Fire from heaven consumed his sacrifice. (1 Kings 18)", difficulty: "medium" },
  { question: "Who received a double portion of Elijah's spirit?", answer: "Elisha. (2 Kings 2:9-12)", difficulty: "medium" },
  { question: "What happened to Lot's wife?", answer: "She looked back and became a pillar of salt. (Genesis 19:26)", difficulty: "medium" },
  { question: "Which book tells the story of the early church?", answer: "The Acts of the Apostles.", difficulty: "medium" },
  { question: "Who wrote the book of Revelation, and where?", answer: "John, on the island of Patmos. (Revelation 1:9)", difficulty: "medium" },
  { question: "Which Roman governor sentenced Jesus?", answer: "Pontius Pilate. (Matthew 27:24-26)", difficulty: "medium" },
  { question: "Jesus healed ten lepers. How many came back to say thank you?", answer: "Only one, a Samaritan. (Luke 17:15-16)", difficulty: "medium" },
  { question: "Who carried Jesus' cross part of the way?", answer: "Simon of Cyrene. (Luke 23:26)", difficulty: "medium" },
  { question: "Which disciple said he would not believe until he touched Jesus' wounds?", answer: "Thomas. (John 20:25)", difficulty: "medium" },
  { question: "What appeared over the disciples at Pentecost?", answer: "Tongues like fire, as the Holy Spirit filled them. (Acts 2:3-4)", difficulty: "medium" },
  { question: "Who was the first Christian martyr?", answer: "Stephen, who was stoned. (Acts 7:59-60)", difficulty: "medium" },
  { question: "Who were the sisters of Lazarus?", answer: "Mary and Martha. (John 11:1-2)", difficulty: "medium" },
  { question: "Which parable features a father running to welcome his lost son home?", answer: "The Prodigal Son. (Luke 15:20)", difficulty: "medium" },
  { question: "In the Good Samaritan parable, who passed by without helping?", answer: "A priest and a Levite. (Luke 10:31-32)", difficulty: "medium" },
  { question: "What tiny seed did Jesus compare the Kingdom of God to?", answer: "A mustard seed. (Matthew 13:31-32)", difficulty: "medium" },
  { question: "How many baskets were left over after feeding the 5,000?", answer: "Twelve baskets. (Matthew 14:20)", difficulty: "medium" },
  { question: "Who built the first temple in Jerusalem?", answer: "King Solomon. (1 Kings 6)", difficulty: "medium" },
  { question: "Which king danced with all his might before the ark?", answer: "David. (2 Samuel 6:14)", difficulty: "medium" },
  { question: "Which prophet saw a valley of dry bones come alive?", answer: "Ezekiel. (Ezekiel 37)", difficulty: "medium" },
  { question: "How did Elijah leave this world?", answer: "Taken to heaven in a whirlwind with chariots of fire. (2 Kings 2:11)", difficulty: "medium" },
  { question: "What was the final plague on Egypt?", answer: "The death of the firstborn. (Exodus 11-12)", difficulty: "medium" },
  { question: "How long did Israel wander in the wilderness?", answer: "Forty years. (Numbers 14:33-34)", difficulty: "medium" },
  { question: "Who was David's loyal best friend?", answer: "Jonathan, son of King Saul. (1 Samuel 18:1)", difficulty: "medium" },
  { question: "Which woman judged Israel and led it to victory?", answer: "Deborah. (Judges 4-5)", difficulty: "medium" },
  { question: "Which two spies trusted God about Canaan?", answer: "Joshua and Caleb. (Numbers 14:6-9)", difficulty: "medium" },
  { question: "What does \"Immanuel\" mean?", answer: "God with us. (Matthew 1:23)", difficulty: "medium" },
  { question: "Who raised Esther as his own daughter?", answer: "Her cousin Mordecai. (Esther 2:7)", difficulty: "medium" },
  { question: "Who came to Jesus at night asking about being born again?", answer: "Nicodemus. (John 3:1-3)", difficulty: "medium" },
  { question: "In which garden did Jesus pray in agony before his arrest?", answer: "Gethsemane. (Matthew 26:36)", difficulty: "medium" },
  { question: "Who first saw the risen Jesus?", answer: "Mary Magdalene. (John 20:14-16)", difficulty: "medium" },
  { question: "What happened in the temple the moment Jesus died?", answer: "The curtain was torn in two from top to bottom. (Matthew 27:51)", difficulty: "medium" },
  { question: "Which prisoner did the crowd choose to free instead of Jesus?", answer: "Barabbas. (Matthew 27:21)", difficulty: "medium" },
  { question: "Which chapter is called the \"love chapter\"?", answer: "1 Corinthians 13.", difficulty: "medium" },
  { question: "Which chapter is called the \"faith chapter\"?", answer: "Hebrews 11.", difficulty: "medium" },
  { question: "What armor does Ephesians 6 tell believers to put on?", answer: "The whole armor of God: truth, righteousness, peace, faith, salvation, and the Word. (Ephesians 6:11-17)", difficulty: "medium" },
  { question: "Who talked with Jesus at a well in Samaria?", answer: "A Samaritan woman. (John 4:7-26)", difficulty: "medium" },
  { question: "On what road did the risen Jesus walk with two disciples?", answer: "The road to Emmaus. (Luke 24:13-15)", difficulty: "medium" },
  { question: "From where did Jesus ascend to heaven?", answer: "The Mount of Olives, near Bethany. (Acts 1:9-12, Luke 24:50)", difficulty: "medium" },
  { question: "How many people were saved when Peter preached at Pentecost?", answer: "About three thousand. (Acts 2:41)", difficulty: "medium" },
  { question: "What did John the Baptist wear and eat?", answer: "Camel's hair clothing; he ate locusts and wild honey. (Matthew 3:4)", difficulty: "medium" },
  { question: "Who was known for great patience through suffering?", answer: "Job. (Job 1-2, James 5:11)", difficulty: "medium" },
  // ----- Additions: hard -----
  { question: "Who was the priest-king of Salem who blessed Abraham?", answer: "Melchizedek. (Genesis 14:18-19)", difficulty: "hard" },
  { question: "Which couple died after lying to the Holy Spirit about their offering?", answer: "Ananias and Sapphira. (Acts 5:1-10)", difficulty: "hard" },
  { question: "Where were believers first called Christians?", answer: "Antioch. (Acts 11:26)", difficulty: "hard" },
  { question: "Who was the blind beggar healed near Jericho?", answer: "Bartimaeus. (Mark 10:46-52)", difficulty: "hard" },
  { question: "Who was Bathsheba's first husband?", answer: "Uriah the Hittite. (2 Samuel 11:3)", difficulty: "hard" },
  { question: "Which left-handed judge defeated King Eglon?", answer: "Ehud. (Judges 3:15-21)", difficulty: "hard" },
  { question: "What is the longest chapter in the Bible?", answer: "Psalm 119, with 176 verses.", difficulty: "hard" },
  { question: "What is the shortest book of the Old Testament?", answer: "Obadiah, with 21 verses.", difficulty: "hard" },
  { question: "How is Ruth related to King David?", answer: "She was his great-grandmother. (Ruth 4:17)", difficulty: "hard" },
  { question: "Under which rabbi did Paul study?", answer: "Gamaliel. (Acts 22:3)", difficulty: "hard" },
  { question: "Which centurion's household did Peter baptize?", answer: "Cornelius, in Caesarea. (Acts 10)", difficulty: "hard" },
  { question: "Which church in Revelation was called lukewarm?", answer: "Laodicea. (Revelation 3:15-16)", difficulty: "hard" },
  { question: "How many churches receive letters in Revelation?", answer: "Seven: Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia, and Laodicea. (Revelation 2-3)", difficulty: "hard" },
  { question: "Who was Methuselah's father, who walked with God?", answer: "Enoch. (Genesis 5:21-24)", difficulty: "hard" },
  { question: "What name meaning \"bitter\" did Naomi ask to be called?", answer: "Mara. (Ruth 1:20)", difficulty: "hard" },
  { question: "Which prophet told David the parable of the poor man's lamb?", answer: "Nathan, confronting him about Bathsheba. (2 Samuel 12:1-7)", difficulty: "hard" },
  { question: "Which queen tested Solomon with hard questions?", answer: "The Queen of Sheba. (1 Kings 10:1)", difficulty: "hard" },
  { question: "In what language was most of the Old Testament written?", answer: "Hebrew, with portions in Aramaic.", difficulty: "hard" },
  { question: "What were the two pillars of Solomon's temple named?", answer: "Jachin and Boaz. (1 Kings 7:21)", difficulty: "hard" },
  { question: "Who were Timothy's faithful mother and grandmother?", answer: "His mother Eunice and grandmother Lois. (2 Timothy 1:5)", difficulty: "hard" },
  { question: "Which sorcerer did Paul strike blind on Cyprus?", answer: "Elymas, also called Bar-Jesus. (Acts 13:6-11)", difficulty: "hard" },
  { question: "Which king got leprosy for burning incense in the temple?", answer: "Uzziah. (2 Chronicles 26:16-19)", difficulty: "hard" },
  { question: "Who stole Laban's household idols?", answer: "Rachel, his daughter. (Genesis 31:19)", difficulty: "hard" },
  { question: "Which Bible book never mentions God by name?", answer: "Esther.", difficulty: "hard" },
  { question: "Which high priest raised the boy Samuel?", answer: "Eli. (1 Samuel 1-3)", difficulty: "hard" },
  { question: "What was Paul's trade?", answer: "Tentmaking, which he shared with Aquila and Priscilla. (Acts 18:3)", difficulty: "hard" },
  { question: "At which pool did Jesus heal a man sick for 38 years?", answer: "The pool of Bethesda. (John 5:2-9)", difficulty: "hard" },
  { question: "Which prophet was a shepherd from Tekoa?", answer: "Amos. (Amos 1:1)", difficulty: "hard" },
  { question: "Which Persian king let the exiles return to rebuild the temple?", answer: "Cyrus. (Ezra 1:1-4)", difficulty: "hard" },
  { question: "Who was the first judge of Israel?", answer: "Othniel, Caleb's nephew. (Judges 3:9-10)", difficulty: "hard" },
  { question: "Which two disciples were both named Simon?", answer: "Simon Peter and Simon the Zealot. (Luke 6:14-15)", difficulty: "hard" },
  { question: "Who fell from a window during Paul's long sermon?", answer: "Eutychus, whom Paul revived. (Acts 20:9-12)", difficulty: "hard" },
  { question: "Who was Ahab's queen who opposed Elijah?", answer: "Jezebel. (1 Kings 19:1-2)", difficulty: "hard" },
  { question: "Which businesswoman of Philippi believed Paul's message?", answer: "Lydia, a seller of purple cloth. (Acts 16:14)", difficulty: "hard" },
  { question: "On which island was Paul shipwrecked?", answer: "Malta. (Acts 28:1)", difficulty: "hard" },
  { question: "Whom did Philip baptize on the road to Gaza?", answer: "An Ethiopian official, treasurer to Queen Candace. (Acts 8:26-39)", difficulty: "hard" },
];

export function shuffleCards<T>(cards: T[], seed?: number): T[] {
  const arr = [...cards];
  let random = seed ?? Math.floor(Math.random() * 2 ** 31);
  const next = () => {
    // Simple LCG for reproducible shuffles when a seed is provided
    random = (random * 1664525 + 1013904223) % 2 ** 32;
    return random / 2 ** 32;
  };
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(next() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
